details:
  namespace: fuse-bookinfo-prd
  image: ghcr.io/fxselazy/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.hellodolphin.in.th
  path: "/fuse(/|$)(.*)"
  # host: bookinfo.opsta.net
  # path: "/student46/details(/|$)(.*)"
  serviceType: ClusterIP