details:
  namespace: fuse-bookinfo-dev
  image: ghcr.io/fxselazy/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.hellodolphin.in.th
  path: "/fuse/details(/|$)(.*)"
  # host: bookinfo.dev.opsta.net
  # path: "/student46/details(/|$)(.*)"
  serviceType: ClusterIP